[project]
name = "correldata"
version = "1.0.0"
description = "Dictionaries of correlated variables"
readme = "readme.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.1",
    "uncertainties>=3.2.2",
]
