[project]
name = "correldata"
version = "2.0.0"
description = "Dataframe-like tables of data with correlated uncertainties"
readme = "readme.md"
authors = [
    { name = "mdaeron", email = "mathieu@daeron.fr" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.1",
    "uncertainties>=3.2.3",
]

[build-system]
requires = [
	"flit_core >=3.2,<4",
    "flit>=3.9.0",
	]
build-backend = "flit_core.buildapi"
