[project]
name = "correldata"
version = "2.0.0b1"
description = "Dataframe-like tables of data with correlated uncertainties"
readme = "readme.md"
license = { "text" = "MIT License: https://opensource.org/licenses/MIT" }
authors = [
    { name = "Mathieu Daëron", email = "mathieu@daeron.fr" }
]
requires-python = ">=3.12"
dependencies = [
    "uncertainties>=3.2.3",
]

[build-system]
requires = ["uv_build>=0.1"]
build-backend = "uv_build"
