[project]
name = "correldata"
version = "2.0.0b4"
description = "Dataframe-like tables of data with correlated uncertainties"
readme = "readme.md"
license = { "text" = "MIT License: https://opensource.org/licenses/MIT" }
authors = [
    { name = "Mathieu Daëron", email = "mathieu@daeron.fr" }
]
requires-python = ">=3.12"
dependencies = [
    "uncertainties>=3.2.3",
]

[project.urls]
Home = "https://github.com/mdaeron/correldata"
Documentation = "https://mdaeron.github.io/correldata"

[build-system]
requires = ["uv_build>=0.1"]
build-backend = "uv_build"

[dependency-groups]
dev = [
	"pdoc>=16.0.0",
	"pytest>=9.0.2",
]

[tool.pytest.ini_options]
filterwarnings = [
	"ignore::pytest.PytestCollectionWarning",
	"ignore::FutureWarning",
]
