__version__     = "2.0.0b1"
__description__ = "Dataframe-like tables of data with correlated uncertainties"
__author__      = "Mathieu Daëron"
__contact__     = "mathieu@daeron.fr"
__license__     = "MIT License: https://opensource.org/licenses/MIT"
__copyright__   = "Mathieu Daëron"
__date__        = "2026-04-04"
